languageCode = "en-us"
title = "Gudang Code"
baseurl = "https://www.gudangcode.com/"

# Agar front-matter pakai format YAML
MetaDataFormat = "yaml"

# untuk apply temanya
themesDir = "themes"
theme = "danatheme"

# Shortname disqus, silahkan sesuaikan
DisqusShortname = "petanikode"

# Untuk Google Analytic, silahkan sesuikan
googleAnalytics = "UA-80517197-1" 

# Untuk deskripsi tag meta di homepage
description = "Blog Programmer pengguna Linux"

# Biodata Author
[author]
    name = "Adi Yudana"
    homepage = "https://adiyudana.com"
    bio = "Founder Gudang Code"
    image = "/img/adi-yudana.jpg"

[permalinks]
    blog = "/:slug/"